FTCRUD/Models/AddCampaignViewModel.cs
namespace FTCRUD.Models
{
    public class AddCampaignViewModel
    {
        public string CampaignName { get; set; }

        public string Keywords { get; set; }

        public decimal BidAmount { get; set; }

        public decimal CampaignFund { get; set; }

        public bool Status { get; set; }

        public string Town { get; set; }

        public int Radius { get; set; }
    }
}

FTCRUD/Models/Domain/Campaign.cs
namespace FTCRUD.Models.Domain
{
    public class Campaign
    {
        public int Id { get; set; }

        public string CampaignName { get; set; }

        public string Keywords { get; set; }

        public decimal BidAmount { get; set; }

        public decimal CampaignFund { get; set; }

        public bool Status { get; set; }

        public string Town { get; set; }

        public int Radius { get; set; }
    }
}

FTCRUD/Models/ErrorViewModel.cs
namespace FTCRUD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FTCRUD/Models/UpdateCampaignViewModel.cs
namespace FTCRUD.Models
{
    public class UpdateCampaignViewModel
    {
        public int Id { get; set; }

        public string CampaignName { get; set; }

        public string Keywords { get; set; }

        public decimal BidAmount { get; set; }

        public decimal CampaignFund { get; set; }

        public bool Status { get; set; }

        public string Town { get; set; }

        public int Radius { get; set; }
    }
}

FTCRUD/Controllers/CampaignsController.cs
using FTCRUD.Data;
using FTCRUD.Models;
using FTCRUD.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.EventSource;

namespace FTCRUD.Controllers
{
    public class CampaignsController : Controller
    {
        private readonly CRUDDbContext crudDbContext;

        public CampaignsController(CRUDDbContext mvCrudDbContext)
        {
            this.crudDbContext = mvCrudDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var campaigns = await crudDbContext.Campaigns.ToListAsync();

            return View(campaigns);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task <IActionResult> Add(AddCampaignViewModel addCampaignRequest)
        {
            var campaign = new Campaign()
            {
                CampaignName = addCampaignRequest.CampaignName,
                Keywords = addCampaignRequest.Keywords,
                BidAmount = addCampaignRequest.BidAmount,
                CampaignFund = addCampaignRequest.CampaignFund,
                Status = addCampaignRequest.Status,
                Town = addCampaignRequest.Town,
                Radius = addCampaignRequest.Radius
            };

            await crudDbContext.Campaigns.AddAsync(campaign);
            await crudDbContext.SaveChangesAsync();

            return RedirectToAction("Add");
        }

        [HttpGet]
        public async Task<IActionResult> View(int id)
        {
            var campaign = await crudDbContext.Campaigns.FirstOrDefaultAsync(c => c.Id == id);

            if (campaign != null)
            {
                var viewModel = new UpdateCampaignViewModel()
                {
                    Id = campaign.Id,
                    CampaignName = campaign.CampaignName,
                    Keywords = campaign.Keywords,
                    BidAmount = campaign.BidAmount,
                    CampaignFund = campaign.CampaignFund,
                    Status = campaign.Status,
                    Town = campaign.Town,
                    Radius = campaign.Radius
                };

                return await Task.Run(() => View("View", viewModel));
            }
            
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateCampaignViewModel model)
        {
            var campaign = await crudDbContext.Campaigns.FindAsync(model.Id);

            if (campaign != null)
            {
                campaign.CampaignName = model.CampaignName;
                campaign.Keywords = model.Keywords;
                campaign.BidAmount = model.BidAmount;
                campaign.CampaignFund = model.CampaignFund;
                campaign.Status = model.Status;
                campaign.Town = model.Town;
                campaign.Radius = model.Radius;

                crudDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateCampaignViewModel model)
        {
            var campaign = await crudDbContext.Campaigns.FindAsync(model.Id);

            if (campaign != null)
            {
                crudDbContext.Campaigns.Remove(campaign);
                await crudDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }
    }
}

FTCRUD/Controllers/HomeController.cs
using FTCRUD.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FTCRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FTCRUD/Views/Campaigns/Add.cshtml
@model FTCRUD.Models.AddCampaignViewModel

@{
}

<h1 class="h1class">Add Campaign</h1>
<form method="post" action="Add" class="mt-5">
    <div class="col-5">
        <label for="" class="form-label">Campaign Name</label>
        <input type="text" class="form-control" asp-for="CampaignName">
    </div>
    <br />

    <div class="col-2">
        <label for="" class="form-label">Keywords</label>
        <input type="text" class="form-control" asp-for="Keywords" placeholder="Company name">
    </div>
    <br />

    <div class="col-2">
        <label for="" class="form-label">Bid Amount</label>
        <input type="decimal" class="form-control" asp-for="BidAmount" placeholder="Funds to spend">
    </div>
    <br />

    <div class="col-2">
        <label for="" class="form-label">Campaign fund</label>
        <input type="decimal" class="form-control" asp-for="CampaignFund">
    </div>
    <br />

    <div>
        <input type="checkbox" class="form-check-input" asp-for="Status">
        <label for="" class="form-check-label">Campaign Status ON/OFF</label>
    </div>
    <br />

    <div class="col-2">
        <label class="form-label">Town</label>
        <select asp-for="Town" class="form-select">
            <option value="Warsaw">Warsaw</option>
            <option value="Cracow" selected="">Cracow</option>
            <option value="Wrocław">Wrocław</option>
            <option value="Poznań">Poznań</option>
            <option value="Gdańsk">Gdańsk</option>
            <option value="Rzeszów">Rzeszów</option>
            <option value="Łódź">Łódź</option>
            <option value="Tarnów">Tarnów</option>
        </select>
    </div>
    <br />
    
    <label for="" class="form-label">Radius</label>
    <div class="col-3 d-flex">
        <input type="range" class="form-range" id="slider" asp-for="Radius" min=25 max=300 step="5">
        <div id="rangeValue">160</div>
    </div>
    <br />

    <script>
        var slider = document.getElementById('slider');
        var value = document.getElementById('value');

        slider.oninput = function () {
            rangeValue.innerHTML = this.value;
        }
    </script>

    <div>
        <button type="submit" class="btn btn-primary">Create Campaign</button>
    </div>
</form>

FTCRUD/Views/Campaigns/Index.cshtml
@using FTCRUD.Models.Domain
@model List<FTCRUD.Models.Domain.Campaign>

@{
}

<h1 class="h1class">Campaigns</h1>

<table class="campTable">
    <thead>
    <tr>
        <th>Campaign Name</th>
        <th>Keywords</th>
        <th>Bid Amount</th>
        <th>Campaign Fund</th>
        <th>Status</th>
        <th>Town</th>
        <th>Radius</th>
        <th></th>
    </tr>
    </thead>

    <tbody>
        @foreach (var campaign in Model)
        {
            <tr>
                <td>@campaign.CampaignName</td>
                <td>@campaign.Keywords</td>
                <td>@campaign.BidAmount</td>
                <td>@campaign.CampaignFund</td>
                @if (campaign.Status == true)
                {
                    <td>Active</td>
                }
                else
                {
                    <td>Unactive</td>
                }
                <td>@campaign.Town</td>
                <td>@campaign.Radius</td>
                <td><a href="Campaigns/View/@campaign.Id">View</a></td>
            </tr>
        }
    </tbody>
</table>

FTCRUD/Views/Campaigns/View.cshtml
@using FTCRUD.Models.Domain
@model FTCRUD.Models.UpdateCampaignViewModel

@{
}

<h1 class="h1class">Edit Campaign Details</h1>
<form method="post" action="View" class="mt-5">
    <div class="col-5">
        <label  class="form-label">ID</label>
        <input type="text" class="form-control" asp-for="Id" readonly>
    </div>
    <br />

    <div class="col-5">
        <label  class="form-label">Campaign Name</label>
        <input type="text" class="form-control" asp-for="CampaignName">
    </div>
    <br/>

    <div class="col-2">
        <label  class="form-label">Keywords</label>
        <input type="text" class="form-control" asp-for="Keywords" placeholder="Company name">
    </div>
    <br/>

    <div class="col-2">
        <label  class="form-label">Bid Amount</label>
        <input type="decimal" class="form-control" asp-for="BidAmount" placeholder="Funds to spend">
    </div>
    <br/>

    <div class="col-2">
        <label class="form-label">Campaign fund</label>
        <input type="decimal" class="form-control" asp-for="CampaignFund">
    </div>
    <br/>

    <div>
        <input type="checkbox" class="form-check-input" asp-for="Status">
        <label class="form-check-label">Campaign Status ON/OFF</label>
    </div>
    <br/>

    <div class="col-2">
        <label class="form-label">Town</label>
        <select asp-for="Town" class="form-select">
            <option value="Warsaw">Warsaw</option>
            <option value="Cracow" selected="">Cracow</option>
            <option value="Wrocław">Wrocław</option>
            <option value="Poznań">Poznań</option>
            <option value="Gdańsk">Gdańsk</option>
            <option value="Rzeszów">Rzeszów</option>
            <option value="Łódź">Łódź</option>
            <option value="Tarnów">Tarnów</option>
        </select>
    </div>
    <br/>

    <label for="" class="form-label">Radius</label>
    <div class="col-3 d-flex">
        <input type="range" class="form-range" id="slider" asp-for="Radius" min=25 max=300 step="5">
        <div id="rangeValue">@ViewData.Model.Radius</div>
    </div>
    <br />

    <script>
        var slider = document.getElementById('slider');
        var value = document.getElementById('value');

        slider.oninput = function () {
            rangeValue.innerHTML = this.value;
        }
    </script>

    <div class="col-12">
        <button type="submit" class="btn btn-primary">Update Campaign</button>
        <button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="Campaigns">Delete Campaign</button>
    </div>
</form>

FTCRUD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Simple CRUD";
}

<div class="text-center">
    <h3 class="display-4">FuturumTech CRUD</h3>
</div>

FTCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FT CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FTCRUD.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Campaigns" asp-action="Index">Campaigns</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Campaigns" asp-action="Add">Add Campaign</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FTCRUD
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>